// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message/Pull.proto

package com.rabbitmq.protocol.message;

public final class PullOuterClass {
  private PullOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PullOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Pull)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string consumerGroup = 1;</code>
     * @return The consumerGroup.
     */
    java.lang.String getConsumerGroup();
    /**
     * <code>string consumerGroup = 1;</code>
     * @return The bytes for consumerGroup.
     */
    com.google.protobuf.ByteString
        getConsumerGroupBytes();

    /**
     * <code>string queueId = 2;</code>
     * @return The queueId.
     */
    java.lang.String getQueueId();
    /**
     * <code>string queueId = 2;</code>
     * @return The bytes for queueId.
     */
    com.google.protobuf.ByteString
        getQueueIdBytes();

    /**
     * <code>string topic = 3;</code>
     * @return The topic.
     */
    java.lang.String getTopic();
    /**
     * <code>string topic = 3;</code>
     * @return The bytes for topic.
     */
    com.google.protobuf.ByteString
        getTopicBytes();

    /**
     * <code>int32 size = 4;</code>
     * @return The size.
     */
    int getSize();

    /**
     * <code>int64 offset = 5;</code>
     * @return The offset.
     */
    long getOffset();

    /**
     * <code>string tags = 6;</code>
     * @return The tags.
     */
    java.lang.String getTags();
    /**
     * <code>string tags = 6;</code>
     * @return The bytes for tags.
     */
    com.google.protobuf.ByteString
        getTagsBytes();
  }
  /**
   * Protobuf type {@code Pull}
   */
  public static final class Pull extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Pull)
      PullOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Pull.newBuilder() to construct.
    private Pull(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Pull() {
      consumerGroup_ = "";
      queueId_ = "";
      topic_ = "";
      tags_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Pull();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Pull(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              consumerGroup_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              queueId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              topic_ = s;
              break;
            }
            case 32: {

              size_ = input.readInt32();
              break;
            }
            case 40: {

              offset_ = input.readInt64();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              tags_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rabbitmq.protocol.message.PullOuterClass.internal_static_Pull_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rabbitmq.protocol.message.PullOuterClass.internal_static_Pull_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rabbitmq.protocol.message.PullOuterClass.Pull.class, com.rabbitmq.protocol.message.PullOuterClass.Pull.Builder.class);
    }

    public static final int CONSUMERGROUP_FIELD_NUMBER = 1;
    private volatile java.lang.Object consumerGroup_;
    /**
     * <code>string consumerGroup = 1;</code>
     * @return The consumerGroup.
     */
    @java.lang.Override
    public java.lang.String getConsumerGroup() {
      java.lang.Object ref = consumerGroup_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        consumerGroup_ = s;
        return s;
      }
    }
    /**
     * <code>string consumerGroup = 1;</code>
     * @return The bytes for consumerGroup.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConsumerGroupBytes() {
      java.lang.Object ref = consumerGroup_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        consumerGroup_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUEUEID_FIELD_NUMBER = 2;
    private volatile java.lang.Object queueId_;
    /**
     * <code>string queueId = 2;</code>
     * @return The queueId.
     */
    @java.lang.Override
    public java.lang.String getQueueId() {
      java.lang.Object ref = queueId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        queueId_ = s;
        return s;
      }
    }
    /**
     * <code>string queueId = 2;</code>
     * @return The bytes for queueId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getQueueIdBytes() {
      java.lang.Object ref = queueId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        queueId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOPIC_FIELD_NUMBER = 3;
    private volatile java.lang.Object topic_;
    /**
     * <code>string topic = 3;</code>
     * @return The topic.
     */
    @java.lang.Override
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      }
    }
    /**
     * <code>string topic = 3;</code>
     * @return The bytes for topic.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIZE_FIELD_NUMBER = 4;
    private int size_;
    /**
     * <code>int32 size = 4;</code>
     * @return The size.
     */
    @java.lang.Override
    public int getSize() {
      return size_;
    }

    public static final int OFFSET_FIELD_NUMBER = 5;
    private long offset_;
    /**
     * <code>int64 offset = 5;</code>
     * @return The offset.
     */
    @java.lang.Override
    public long getOffset() {
      return offset_;
    }

    public static final int TAGS_FIELD_NUMBER = 6;
    private volatile java.lang.Object tags_;
    /**
     * <code>string tags = 6;</code>
     * @return The tags.
     */
    @java.lang.Override
    public java.lang.String getTags() {
      java.lang.Object ref = tags_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tags_ = s;
        return s;
      }
    }
    /**
     * <code>string tags = 6;</code>
     * @return The bytes for tags.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTagsBytes() {
      java.lang.Object ref = tags_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tags_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(consumerGroup_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, consumerGroup_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(queueId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, queueId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, topic_);
      }
      if (size_ != 0) {
        output.writeInt32(4, size_);
      }
      if (offset_ != 0L) {
        output.writeInt64(5, offset_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tags_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, tags_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(consumerGroup_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, consumerGroup_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(queueId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, queueId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, topic_);
      }
      if (size_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, size_);
      }
      if (offset_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, offset_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tags_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, tags_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.rabbitmq.protocol.message.PullOuterClass.Pull)) {
        return super.equals(obj);
      }
      com.rabbitmq.protocol.message.PullOuterClass.Pull other = (com.rabbitmq.protocol.message.PullOuterClass.Pull) obj;

      if (!getConsumerGroup()
          .equals(other.getConsumerGroup())) return false;
      if (!getQueueId()
          .equals(other.getQueueId())) return false;
      if (!getTopic()
          .equals(other.getTopic())) return false;
      if (getSize()
          != other.getSize()) return false;
      if (getOffset()
          != other.getOffset()) return false;
      if (!getTags()
          .equals(other.getTags())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONSUMERGROUP_FIELD_NUMBER;
      hash = (53 * hash) + getConsumerGroup().hashCode();
      hash = (37 * hash) + QUEUEID_FIELD_NUMBER;
      hash = (53 * hash) + getQueueId().hashCode();
      hash = (37 * hash) + TOPIC_FIELD_NUMBER;
      hash = (53 * hash) + getTopic().hashCode();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSize();
      hash = (37 * hash) + OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOffset());
      hash = (37 * hash) + TAGS_FIELD_NUMBER;
      hash = (53 * hash) + getTags().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.rabbitmq.protocol.message.PullOuterClass.Pull parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rabbitmq.protocol.message.PullOuterClass.Pull parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rabbitmq.protocol.message.PullOuterClass.Pull parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rabbitmq.protocol.message.PullOuterClass.Pull parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rabbitmq.protocol.message.PullOuterClass.Pull parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rabbitmq.protocol.message.PullOuterClass.Pull parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rabbitmq.protocol.message.PullOuterClass.Pull parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rabbitmq.protocol.message.PullOuterClass.Pull parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rabbitmq.protocol.message.PullOuterClass.Pull parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.rabbitmq.protocol.message.PullOuterClass.Pull parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rabbitmq.protocol.message.PullOuterClass.Pull parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rabbitmq.protocol.message.PullOuterClass.Pull parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.rabbitmq.protocol.message.PullOuterClass.Pull prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Pull}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Pull)
        com.rabbitmq.protocol.message.PullOuterClass.PullOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rabbitmq.protocol.message.PullOuterClass.internal_static_Pull_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rabbitmq.protocol.message.PullOuterClass.internal_static_Pull_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rabbitmq.protocol.message.PullOuterClass.Pull.class, com.rabbitmq.protocol.message.PullOuterClass.Pull.Builder.class);
      }

      // Construct using com.rabbitmq.protocol.message.PullOuterClass.Pull.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        consumerGroup_ = "";

        queueId_ = "";

        topic_ = "";

        size_ = 0;

        offset_ = 0L;

        tags_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rabbitmq.protocol.message.PullOuterClass.internal_static_Pull_descriptor;
      }

      @java.lang.Override
      public com.rabbitmq.protocol.message.PullOuterClass.Pull getDefaultInstanceForType() {
        return com.rabbitmq.protocol.message.PullOuterClass.Pull.getDefaultInstance();
      }

      @java.lang.Override
      public com.rabbitmq.protocol.message.PullOuterClass.Pull build() {
        com.rabbitmq.protocol.message.PullOuterClass.Pull result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.rabbitmq.protocol.message.PullOuterClass.Pull buildPartial() {
        com.rabbitmq.protocol.message.PullOuterClass.Pull result = new com.rabbitmq.protocol.message.PullOuterClass.Pull(this);
        result.consumerGroup_ = consumerGroup_;
        result.queueId_ = queueId_;
        result.topic_ = topic_;
        result.size_ = size_;
        result.offset_ = offset_;
        result.tags_ = tags_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rabbitmq.protocol.message.PullOuterClass.Pull) {
          return mergeFrom((com.rabbitmq.protocol.message.PullOuterClass.Pull)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rabbitmq.protocol.message.PullOuterClass.Pull other) {
        if (other == com.rabbitmq.protocol.message.PullOuterClass.Pull.getDefaultInstance()) return this;
        if (!other.getConsumerGroup().isEmpty()) {
          consumerGroup_ = other.consumerGroup_;
          onChanged();
        }
        if (!other.getQueueId().isEmpty()) {
          queueId_ = other.queueId_;
          onChanged();
        }
        if (!other.getTopic().isEmpty()) {
          topic_ = other.topic_;
          onChanged();
        }
        if (other.getSize() != 0) {
          setSize(other.getSize());
        }
        if (other.getOffset() != 0L) {
          setOffset(other.getOffset());
        }
        if (!other.getTags().isEmpty()) {
          tags_ = other.tags_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rabbitmq.protocol.message.PullOuterClass.Pull parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rabbitmq.protocol.message.PullOuterClass.Pull) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object consumerGroup_ = "";
      /**
       * <code>string consumerGroup = 1;</code>
       * @return The consumerGroup.
       */
      public java.lang.String getConsumerGroup() {
        java.lang.Object ref = consumerGroup_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          consumerGroup_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string consumerGroup = 1;</code>
       * @return The bytes for consumerGroup.
       */
      public com.google.protobuf.ByteString
          getConsumerGroupBytes() {
        java.lang.Object ref = consumerGroup_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          consumerGroup_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string consumerGroup = 1;</code>
       * @param value The consumerGroup to set.
       * @return This builder for chaining.
       */
      public Builder setConsumerGroup(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        consumerGroup_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string consumerGroup = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearConsumerGroup() {
        
        consumerGroup_ = getDefaultInstance().getConsumerGroup();
        onChanged();
        return this;
      }
      /**
       * <code>string consumerGroup = 1;</code>
       * @param value The bytes for consumerGroup to set.
       * @return This builder for chaining.
       */
      public Builder setConsumerGroupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        consumerGroup_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object queueId_ = "";
      /**
       * <code>string queueId = 2;</code>
       * @return The queueId.
       */
      public java.lang.String getQueueId() {
        java.lang.Object ref = queueId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          queueId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string queueId = 2;</code>
       * @return The bytes for queueId.
       */
      public com.google.protobuf.ByteString
          getQueueIdBytes() {
        java.lang.Object ref = queueId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          queueId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string queueId = 2;</code>
       * @param value The queueId to set.
       * @return This builder for chaining.
       */
      public Builder setQueueId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        queueId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string queueId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearQueueId() {
        
        queueId_ = getDefaultInstance().getQueueId();
        onChanged();
        return this;
      }
      /**
       * <code>string queueId = 2;</code>
       * @param value The bytes for queueId to set.
       * @return This builder for chaining.
       */
      public Builder setQueueIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        queueId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object topic_ = "";
      /**
       * <code>string topic = 3;</code>
       * @return The topic.
       */
      public java.lang.String getTopic() {
        java.lang.Object ref = topic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          topic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string topic = 3;</code>
       * @return The bytes for topic.
       */
      public com.google.protobuf.ByteString
          getTopicBytes() {
        java.lang.Object ref = topic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string topic = 3;</code>
       * @param value The topic to set.
       * @return This builder for chaining.
       */
      public Builder setTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        topic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string topic = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTopic() {
        
        topic_ = getDefaultInstance().getTopic();
        onChanged();
        return this;
      }
      /**
       * <code>string topic = 3;</code>
       * @param value The bytes for topic to set.
       * @return This builder for chaining.
       */
      public Builder setTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        topic_ = value;
        onChanged();
        return this;
      }

      private int size_ ;
      /**
       * <code>int32 size = 4;</code>
       * @return The size.
       */
      @java.lang.Override
      public int getSize() {
        return size_;
      }
      /**
       * <code>int32 size = 4;</code>
       * @param value The size to set.
       * @return This builder for chaining.
       */
      public Builder setSize(int value) {
        
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 size = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSize() {
        
        size_ = 0;
        onChanged();
        return this;
      }

      private long offset_ ;
      /**
       * <code>int64 offset = 5;</code>
       * @return The offset.
       */
      @java.lang.Override
      public long getOffset() {
        return offset_;
      }
      /**
       * <code>int64 offset = 5;</code>
       * @param value The offset to set.
       * @return This builder for chaining.
       */
      public Builder setOffset(long value) {
        
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 offset = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearOffset() {
        
        offset_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object tags_ = "";
      /**
       * <code>string tags = 6;</code>
       * @return The tags.
       */
      public java.lang.String getTags() {
        java.lang.Object ref = tags_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tags_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tags = 6;</code>
       * @return The bytes for tags.
       */
      public com.google.protobuf.ByteString
          getTagsBytes() {
        java.lang.Object ref = tags_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tags_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tags = 6;</code>
       * @param value The tags to set.
       * @return This builder for chaining.
       */
      public Builder setTags(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tags_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tags = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTags() {
        
        tags_ = getDefaultInstance().getTags();
        onChanged();
        return this;
      }
      /**
       * <code>string tags = 6;</code>
       * @param value The bytes for tags to set.
       * @return This builder for chaining.
       */
      public Builder setTagsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tags_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Pull)
    }

    // @@protoc_insertion_point(class_scope:Pull)
    private static final com.rabbitmq.protocol.message.PullOuterClass.Pull DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.rabbitmq.protocol.message.PullOuterClass.Pull();
    }

    public static com.rabbitmq.protocol.message.PullOuterClass.Pull getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Pull>
        PARSER = new com.google.protobuf.AbstractParser<Pull>() {
      @java.lang.Override
      public Pull parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Pull(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Pull> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Pull> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.rabbitmq.protocol.message.PullOuterClass.Pull getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Pull_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Pull_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022message/Pull.proto\"i\n\004Pull\022\025\n\rconsumer" +
      "Group\030\001 \001(\t\022\017\n\007queueId\030\002 \001(\t\022\r\n\005topic\030\003 " +
      "\001(\t\022\014\n\004size\030\004 \001(\005\022\016\n\006offset\030\005 \001(\003\022\014\n\004tag" +
      "s\030\006 \001(\tB\037\n\035com.rabbitmq.protocol.message" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Pull_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Pull_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Pull_descriptor,
        new java.lang.String[] { "ConsumerGroup", "QueueId", "Topic", "Size", "Offset", "Tags", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
