// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message/PullMessageResp.proto

package com.rabbitmq.protocol.message;

public final class PullMessageRespOuterClass {
  private PullMessageRespOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PullMessageRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PullMessageResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .PullMessage pullMessage = 1;</code>
     */
    java.util.List<com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage> 
        getPullMessageList();
    /**
     * <code>repeated .PullMessage pullMessage = 1;</code>
     */
    com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage getPullMessage(int index);
    /**
     * <code>repeated .PullMessage pullMessage = 1;</code>
     */
    int getPullMessageCount();
    /**
     * <code>repeated .PullMessage pullMessage = 1;</code>
     */
    java.util.List<? extends com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessageOrBuilder> 
        getPullMessageOrBuilderList();
    /**
     * <code>repeated .PullMessage pullMessage = 1;</code>
     */
    com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessageOrBuilder getPullMessageOrBuilder(
        int index);

    /**
     * <code>string topic = 2;</code>
     * @return The topic.
     */
    java.lang.String getTopic();
    /**
     * <code>string topic = 2;</code>
     * @return The bytes for topic.
     */
    com.google.protobuf.ByteString
        getTopicBytes();

    /**
     * <code>string consumerGroup = 3;</code>
     * @return The consumerGroup.
     */
    java.lang.String getConsumerGroup();
    /**
     * <code>string consumerGroup = 3;</code>
     * @return The bytes for consumerGroup.
     */
    com.google.protobuf.ByteString
        getConsumerGroupBytes();

    /**
     * <code>int32 queueId = 4;</code>
     * @return The queueId.
     */
    int getQueueId();

    /**
     * <code>int64 lastIndex = 5;</code>
     * @return The lastIndex.
     */
    long getLastIndex();
  }
  /**
   * Protobuf type {@code PullMessageResp}
   */
  public static final class PullMessageResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PullMessageResp)
      PullMessageRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PullMessageResp.newBuilder() to construct.
    private PullMessageResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PullMessageResp() {
      pullMessage_ = java.util.Collections.emptyList();
      topic_ = "";
      consumerGroup_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PullMessageResp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PullMessageResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                pullMessage_ = new java.util.ArrayList<com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              pullMessage_.add(
                  input.readMessage(com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage.parser(), extensionRegistry));
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              topic_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              consumerGroup_ = s;
              break;
            }
            case 32: {

              queueId_ = input.readInt32();
              break;
            }
            case 40: {

              lastIndex_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          pullMessage_ = java.util.Collections.unmodifiableList(pullMessage_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rabbitmq.protocol.message.PullMessageRespOuterClass.internal_static_PullMessageResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rabbitmq.protocol.message.PullMessageRespOuterClass.internal_static_PullMessageResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp.class, com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp.Builder.class);
    }

    public static final int PULLMESSAGE_FIELD_NUMBER = 1;
    private java.util.List<com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage> pullMessage_;
    /**
     * <code>repeated .PullMessage pullMessage = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage> getPullMessageList() {
      return pullMessage_;
    }
    /**
     * <code>repeated .PullMessage pullMessage = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessageOrBuilder> 
        getPullMessageOrBuilderList() {
      return pullMessage_;
    }
    /**
     * <code>repeated .PullMessage pullMessage = 1;</code>
     */
    @java.lang.Override
    public int getPullMessageCount() {
      return pullMessage_.size();
    }
    /**
     * <code>repeated .PullMessage pullMessage = 1;</code>
     */
    @java.lang.Override
    public com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage getPullMessage(int index) {
      return pullMessage_.get(index);
    }
    /**
     * <code>repeated .PullMessage pullMessage = 1;</code>
     */
    @java.lang.Override
    public com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessageOrBuilder getPullMessageOrBuilder(
        int index) {
      return pullMessage_.get(index);
    }

    public static final int TOPIC_FIELD_NUMBER = 2;
    private volatile java.lang.Object topic_;
    /**
     * <code>string topic = 2;</code>
     * @return The topic.
     */
    @java.lang.Override
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      }
    }
    /**
     * <code>string topic = 2;</code>
     * @return The bytes for topic.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONSUMERGROUP_FIELD_NUMBER = 3;
    private volatile java.lang.Object consumerGroup_;
    /**
     * <code>string consumerGroup = 3;</code>
     * @return The consumerGroup.
     */
    @java.lang.Override
    public java.lang.String getConsumerGroup() {
      java.lang.Object ref = consumerGroup_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        consumerGroup_ = s;
        return s;
      }
    }
    /**
     * <code>string consumerGroup = 3;</code>
     * @return The bytes for consumerGroup.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConsumerGroupBytes() {
      java.lang.Object ref = consumerGroup_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        consumerGroup_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUEUEID_FIELD_NUMBER = 4;
    private int queueId_;
    /**
     * <code>int32 queueId = 4;</code>
     * @return The queueId.
     */
    @java.lang.Override
    public int getQueueId() {
      return queueId_;
    }

    public static final int LASTINDEX_FIELD_NUMBER = 5;
    private long lastIndex_;
    /**
     * <code>int64 lastIndex = 5;</code>
     * @return The lastIndex.
     */
    @java.lang.Override
    public long getLastIndex() {
      return lastIndex_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < pullMessage_.size(); i++) {
        output.writeMessage(1, pullMessage_.get(i));
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, topic_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(consumerGroup_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, consumerGroup_);
      }
      if (queueId_ != 0) {
        output.writeInt32(4, queueId_);
      }
      if (lastIndex_ != 0L) {
        output.writeInt64(5, lastIndex_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < pullMessage_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, pullMessage_.get(i));
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, topic_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(consumerGroup_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, consumerGroup_);
      }
      if (queueId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, queueId_);
      }
      if (lastIndex_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, lastIndex_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp)) {
        return super.equals(obj);
      }
      com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp other = (com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp) obj;

      if (!getPullMessageList()
          .equals(other.getPullMessageList())) return false;
      if (!getTopic()
          .equals(other.getTopic())) return false;
      if (!getConsumerGroup()
          .equals(other.getConsumerGroup())) return false;
      if (getQueueId()
          != other.getQueueId()) return false;
      if (getLastIndex()
          != other.getLastIndex()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPullMessageCount() > 0) {
        hash = (37 * hash) + PULLMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getPullMessageList().hashCode();
      }
      hash = (37 * hash) + TOPIC_FIELD_NUMBER;
      hash = (53 * hash) + getTopic().hashCode();
      hash = (37 * hash) + CONSUMERGROUP_FIELD_NUMBER;
      hash = (53 * hash) + getConsumerGroup().hashCode();
      hash = (37 * hash) + QUEUEID_FIELD_NUMBER;
      hash = (53 * hash) + getQueueId();
      hash = (37 * hash) + LASTINDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastIndex());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PullMessageResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PullMessageResp)
        com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rabbitmq.protocol.message.PullMessageRespOuterClass.internal_static_PullMessageResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rabbitmq.protocol.message.PullMessageRespOuterClass.internal_static_PullMessageResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp.class, com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp.Builder.class);
      }

      // Construct using com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPullMessageFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (pullMessageBuilder_ == null) {
          pullMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          pullMessageBuilder_.clear();
        }
        topic_ = "";

        consumerGroup_ = "";

        queueId_ = 0;

        lastIndex_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rabbitmq.protocol.message.PullMessageRespOuterClass.internal_static_PullMessageResp_descriptor;
      }

      @java.lang.Override
      public com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp getDefaultInstanceForType() {
        return com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp.getDefaultInstance();
      }

      @java.lang.Override
      public com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp build() {
        com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp buildPartial() {
        com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp result = new com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp(this);
        int from_bitField0_ = bitField0_;
        if (pullMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            pullMessage_ = java.util.Collections.unmodifiableList(pullMessage_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.pullMessage_ = pullMessage_;
        } else {
          result.pullMessage_ = pullMessageBuilder_.build();
        }
        result.topic_ = topic_;
        result.consumerGroup_ = consumerGroup_;
        result.queueId_ = queueId_;
        result.lastIndex_ = lastIndex_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp) {
          return mergeFrom((com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp other) {
        if (other == com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp.getDefaultInstance()) return this;
        if (pullMessageBuilder_ == null) {
          if (!other.pullMessage_.isEmpty()) {
            if (pullMessage_.isEmpty()) {
              pullMessage_ = other.pullMessage_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePullMessageIsMutable();
              pullMessage_.addAll(other.pullMessage_);
            }
            onChanged();
          }
        } else {
          if (!other.pullMessage_.isEmpty()) {
            if (pullMessageBuilder_.isEmpty()) {
              pullMessageBuilder_.dispose();
              pullMessageBuilder_ = null;
              pullMessage_ = other.pullMessage_;
              bitField0_ = (bitField0_ & ~0x00000001);
              pullMessageBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPullMessageFieldBuilder() : null;
            } else {
              pullMessageBuilder_.addAllMessages(other.pullMessage_);
            }
          }
        }
        if (!other.getTopic().isEmpty()) {
          topic_ = other.topic_;
          onChanged();
        }
        if (!other.getConsumerGroup().isEmpty()) {
          consumerGroup_ = other.consumerGroup_;
          onChanged();
        }
        if (other.getQueueId() != 0) {
          setQueueId(other.getQueueId());
        }
        if (other.getLastIndex() != 0L) {
          setLastIndex(other.getLastIndex());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage> pullMessage_ =
        java.util.Collections.emptyList();
      private void ensurePullMessageIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          pullMessage_ = new java.util.ArrayList<com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage>(pullMessage_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage, com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage.Builder, com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessageOrBuilder> pullMessageBuilder_;

      /**
       * <code>repeated .PullMessage pullMessage = 1;</code>
       */
      public java.util.List<com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage> getPullMessageList() {
        if (pullMessageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(pullMessage_);
        } else {
          return pullMessageBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .PullMessage pullMessage = 1;</code>
       */
      public int getPullMessageCount() {
        if (pullMessageBuilder_ == null) {
          return pullMessage_.size();
        } else {
          return pullMessageBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .PullMessage pullMessage = 1;</code>
       */
      public com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage getPullMessage(int index) {
        if (pullMessageBuilder_ == null) {
          return pullMessage_.get(index);
        } else {
          return pullMessageBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .PullMessage pullMessage = 1;</code>
       */
      public Builder setPullMessage(
          int index, com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage value) {
        if (pullMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePullMessageIsMutable();
          pullMessage_.set(index, value);
          onChanged();
        } else {
          pullMessageBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PullMessage pullMessage = 1;</code>
       */
      public Builder setPullMessage(
          int index, com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage.Builder builderForValue) {
        if (pullMessageBuilder_ == null) {
          ensurePullMessageIsMutable();
          pullMessage_.set(index, builderForValue.build());
          onChanged();
        } else {
          pullMessageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PullMessage pullMessage = 1;</code>
       */
      public Builder addPullMessage(com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage value) {
        if (pullMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePullMessageIsMutable();
          pullMessage_.add(value);
          onChanged();
        } else {
          pullMessageBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .PullMessage pullMessage = 1;</code>
       */
      public Builder addPullMessage(
          int index, com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage value) {
        if (pullMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePullMessageIsMutable();
          pullMessage_.add(index, value);
          onChanged();
        } else {
          pullMessageBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PullMessage pullMessage = 1;</code>
       */
      public Builder addPullMessage(
          com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage.Builder builderForValue) {
        if (pullMessageBuilder_ == null) {
          ensurePullMessageIsMutable();
          pullMessage_.add(builderForValue.build());
          onChanged();
        } else {
          pullMessageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PullMessage pullMessage = 1;</code>
       */
      public Builder addPullMessage(
          int index, com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage.Builder builderForValue) {
        if (pullMessageBuilder_ == null) {
          ensurePullMessageIsMutable();
          pullMessage_.add(index, builderForValue.build());
          onChanged();
        } else {
          pullMessageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PullMessage pullMessage = 1;</code>
       */
      public Builder addAllPullMessage(
          java.lang.Iterable<? extends com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage> values) {
        if (pullMessageBuilder_ == null) {
          ensurePullMessageIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, pullMessage_);
          onChanged();
        } else {
          pullMessageBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .PullMessage pullMessage = 1;</code>
       */
      public Builder clearPullMessage() {
        if (pullMessageBuilder_ == null) {
          pullMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          pullMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .PullMessage pullMessage = 1;</code>
       */
      public Builder removePullMessage(int index) {
        if (pullMessageBuilder_ == null) {
          ensurePullMessageIsMutable();
          pullMessage_.remove(index);
          onChanged();
        } else {
          pullMessageBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .PullMessage pullMessage = 1;</code>
       */
      public com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage.Builder getPullMessageBuilder(
          int index) {
        return getPullMessageFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .PullMessage pullMessage = 1;</code>
       */
      public com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessageOrBuilder getPullMessageOrBuilder(
          int index) {
        if (pullMessageBuilder_ == null) {
          return pullMessage_.get(index);  } else {
          return pullMessageBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .PullMessage pullMessage = 1;</code>
       */
      public java.util.List<? extends com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessageOrBuilder> 
           getPullMessageOrBuilderList() {
        if (pullMessageBuilder_ != null) {
          return pullMessageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(pullMessage_);
        }
      }
      /**
       * <code>repeated .PullMessage pullMessage = 1;</code>
       */
      public com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage.Builder addPullMessageBuilder() {
        return getPullMessageFieldBuilder().addBuilder(
            com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .PullMessage pullMessage = 1;</code>
       */
      public com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage.Builder addPullMessageBuilder(
          int index) {
        return getPullMessageFieldBuilder().addBuilder(
            index, com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .PullMessage pullMessage = 1;</code>
       */
      public java.util.List<com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage.Builder> 
           getPullMessageBuilderList() {
        return getPullMessageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage, com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage.Builder, com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessageOrBuilder> 
          getPullMessageFieldBuilder() {
        if (pullMessageBuilder_ == null) {
          pullMessageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage, com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessage.Builder, com.rabbitmq.protocol.message.PullMessageOuterClass.PullMessageOrBuilder>(
                  pullMessage_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          pullMessage_ = null;
        }
        return pullMessageBuilder_;
      }

      private java.lang.Object topic_ = "";
      /**
       * <code>string topic = 2;</code>
       * @return The topic.
       */
      public java.lang.String getTopic() {
        java.lang.Object ref = topic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          topic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string topic = 2;</code>
       * @return The bytes for topic.
       */
      public com.google.protobuf.ByteString
          getTopicBytes() {
        java.lang.Object ref = topic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string topic = 2;</code>
       * @param value The topic to set.
       * @return This builder for chaining.
       */
      public Builder setTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        topic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string topic = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTopic() {
        
        topic_ = getDefaultInstance().getTopic();
        onChanged();
        return this;
      }
      /**
       * <code>string topic = 2;</code>
       * @param value The bytes for topic to set.
       * @return This builder for chaining.
       */
      public Builder setTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        topic_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object consumerGroup_ = "";
      /**
       * <code>string consumerGroup = 3;</code>
       * @return The consumerGroup.
       */
      public java.lang.String getConsumerGroup() {
        java.lang.Object ref = consumerGroup_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          consumerGroup_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string consumerGroup = 3;</code>
       * @return The bytes for consumerGroup.
       */
      public com.google.protobuf.ByteString
          getConsumerGroupBytes() {
        java.lang.Object ref = consumerGroup_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          consumerGroup_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string consumerGroup = 3;</code>
       * @param value The consumerGroup to set.
       * @return This builder for chaining.
       */
      public Builder setConsumerGroup(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        consumerGroup_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string consumerGroup = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearConsumerGroup() {
        
        consumerGroup_ = getDefaultInstance().getConsumerGroup();
        onChanged();
        return this;
      }
      /**
       * <code>string consumerGroup = 3;</code>
       * @param value The bytes for consumerGroup to set.
       * @return This builder for chaining.
       */
      public Builder setConsumerGroupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        consumerGroup_ = value;
        onChanged();
        return this;
      }

      private int queueId_ ;
      /**
       * <code>int32 queueId = 4;</code>
       * @return The queueId.
       */
      @java.lang.Override
      public int getQueueId() {
        return queueId_;
      }
      /**
       * <code>int32 queueId = 4;</code>
       * @param value The queueId to set.
       * @return This builder for chaining.
       */
      public Builder setQueueId(int value) {
        
        queueId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 queueId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearQueueId() {
        
        queueId_ = 0;
        onChanged();
        return this;
      }

      private long lastIndex_ ;
      /**
       * <code>int64 lastIndex = 5;</code>
       * @return The lastIndex.
       */
      @java.lang.Override
      public long getLastIndex() {
        return lastIndex_;
      }
      /**
       * <code>int64 lastIndex = 5;</code>
       * @param value The lastIndex to set.
       * @return This builder for chaining.
       */
      public Builder setLastIndex(long value) {
        
        lastIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 lastIndex = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastIndex() {
        
        lastIndex_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PullMessageResp)
    }

    // @@protoc_insertion_point(class_scope:PullMessageResp)
    private static final com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp();
    }

    public static com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PullMessageResp>
        PARSER = new com.google.protobuf.AbstractParser<PullMessageResp>() {
      @java.lang.Override
      public PullMessageResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PullMessageResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PullMessageResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PullMessageResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.rabbitmq.protocol.message.PullMessageRespOuterClass.PullMessageResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PullMessageResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PullMessageResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035message/PullMessageResp.proto\032\031message" +
      "/PullMessage.proto\"~\n\017PullMessageResp\022!\n" +
      "\013pullMessage\030\001 \003(\0132\014.PullMessage\022\r\n\005topi" +
      "c\030\002 \001(\t\022\025\n\rconsumerGroup\030\003 \001(\t\022\017\n\007queueI" +
      "d\030\004 \001(\005\022\021\n\tlastIndex\030\005 \001(\003B\037\n\035com.rabbit" +
      "mq.protocol.messageP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.rabbitmq.protocol.message.PullMessageOuterClass.getDescriptor(),
        });
    internal_static_PullMessageResp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PullMessageResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PullMessageResp_descriptor,
        new java.lang.String[] { "PullMessage", "Topic", "ConsumerGroup", "QueueId", "LastIndex", });
    com.rabbitmq.protocol.message.PullMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
