// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message/SyncOffsetMessage.proto

package com.rabbitmq.protocol.message;

public final class SyncOffsetMessageOuterClass {
  private SyncOffsetMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SyncOffsetMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SyncOffsetMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string consumer = 1;</code>
     * @return The consumer.
     */
    java.lang.String getConsumer();
    /**
     * <code>string consumer = 1;</code>
     * @return The bytes for consumer.
     */
    com.google.protobuf.ByteString
        getConsumerBytes();

    /**
     * <code>string topic = 2;</code>
     * @return The topic.
     */
    java.lang.String getTopic();
    /**
     * <code>string topic = 2;</code>
     * @return The bytes for topic.
     */
    com.google.protobuf.ByteString
        getTopicBytes();

    /**
     * <code>map&lt;int32, int64&gt; offsetMap = 3;</code>
     */
    int getOffsetMapCount();
    /**
     * <code>map&lt;int32, int64&gt; offsetMap = 3;</code>
     */
    boolean containsOffsetMap(
        int key);
    /**
     * Use {@link #getOffsetMapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, java.lang.Long>
    getOffsetMap();
    /**
     * <code>map&lt;int32, int64&gt; offsetMap = 3;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.Long>
    getOffsetMapMap();
    /**
     * <code>map&lt;int32, int64&gt; offsetMap = 3;</code>
     */

    long getOffsetMapOrDefault(
        int key,
        long defaultValue);
    /**
     * <code>map&lt;int32, int64&gt; offsetMap = 3;</code>
     */

    long getOffsetMapOrThrow(
        int key);
  }
  /**
   * Protobuf type {@code SyncOffsetMessage}
   */
  public static final class SyncOffsetMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SyncOffsetMessage)
      SyncOffsetMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SyncOffsetMessage.newBuilder() to construct.
    private SyncOffsetMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SyncOffsetMessage() {
      consumer_ = "";
      topic_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SyncOffsetMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SyncOffsetMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              consumer_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              topic_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                offsetMap_ = com.google.protobuf.MapField.newMapField(
                    OffsetMapDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Long>
              offsetMap__ = input.readMessage(
                  OffsetMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              offsetMap_.getMutableMap().put(
                  offsetMap__.getKey(), offsetMap__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.internal_static_SyncOffsetMessage_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetOffsetMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.internal_static_SyncOffsetMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage.class, com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage.Builder.class);
    }

    public static final int CONSUMER_FIELD_NUMBER = 1;
    private volatile java.lang.Object consumer_;
    /**
     * <code>string consumer = 1;</code>
     * @return The consumer.
     */
    @java.lang.Override
    public java.lang.String getConsumer() {
      java.lang.Object ref = consumer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        consumer_ = s;
        return s;
      }
    }
    /**
     * <code>string consumer = 1;</code>
     * @return The bytes for consumer.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConsumerBytes() {
      java.lang.Object ref = consumer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        consumer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOPIC_FIELD_NUMBER = 2;
    private volatile java.lang.Object topic_;
    /**
     * <code>string topic = 2;</code>
     * @return The topic.
     */
    @java.lang.Override
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      }
    }
    /**
     * <code>string topic = 2;</code>
     * @return The bytes for topic.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OFFSETMAP_FIELD_NUMBER = 3;
    private static final class OffsetMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.Long> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.Long>newDefaultInstance(
                  com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.internal_static_SyncOffsetMessage_OffsetMapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.INT64,
                  0L);
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Long> offsetMap_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Long>
    internalGetOffsetMap() {
      if (offsetMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            OffsetMapDefaultEntryHolder.defaultEntry);
      }
      return offsetMap_;
    }

    public int getOffsetMapCount() {
      return internalGetOffsetMap().getMap().size();
    }
    /**
     * <code>map&lt;int32, int64&gt; offsetMap = 3;</code>
     */

    @java.lang.Override
    public boolean containsOffsetMap(
        int key) {
      
      return internalGetOffsetMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getOffsetMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Long> getOffsetMap() {
      return getOffsetMapMap();
    }
    /**
     * <code>map&lt;int32, int64&gt; offsetMap = 3;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Integer, java.lang.Long> getOffsetMapMap() {
      return internalGetOffsetMap().getMap();
    }
    /**
     * <code>map&lt;int32, int64&gt; offsetMap = 3;</code>
     */
    @java.lang.Override

    public long getOffsetMapOrDefault(
        int key,
        long defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.Long> map =
          internalGetOffsetMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, int64&gt; offsetMap = 3;</code>
     */
    @java.lang.Override

    public long getOffsetMapOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.Long> map =
          internalGetOffsetMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(consumer_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, consumer_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, topic_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetOffsetMap(),
          OffsetMapDefaultEntryHolder.defaultEntry,
          3);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(consumer_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, consumer_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, topic_);
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.Long> entry
           : internalGetOffsetMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Long>
        offsetMap__ = OffsetMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, offsetMap__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage)) {
        return super.equals(obj);
      }
      com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage other = (com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage) obj;

      if (!getConsumer()
          .equals(other.getConsumer())) return false;
      if (!getTopic()
          .equals(other.getTopic())) return false;
      if (!internalGetOffsetMap().equals(
          other.internalGetOffsetMap())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONSUMER_FIELD_NUMBER;
      hash = (53 * hash) + getConsumer().hashCode();
      hash = (37 * hash) + TOPIC_FIELD_NUMBER;
      hash = (53 * hash) + getTopic().hashCode();
      if (!internalGetOffsetMap().getMap().isEmpty()) {
        hash = (37 * hash) + OFFSETMAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetOffsetMap().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SyncOffsetMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SyncOffsetMessage)
        com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.internal_static_SyncOffsetMessage_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetOffsetMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableOffsetMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.internal_static_SyncOffsetMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage.class, com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage.Builder.class);
      }

      // Construct using com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        consumer_ = "";

        topic_ = "";

        internalGetMutableOffsetMap().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.internal_static_SyncOffsetMessage_descriptor;
      }

      @java.lang.Override
      public com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage getDefaultInstanceForType() {
        return com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage build() {
        com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage buildPartial() {
        com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage result = new com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage(this);
        int from_bitField0_ = bitField0_;
        result.consumer_ = consumer_;
        result.topic_ = topic_;
        result.offsetMap_ = internalGetOffsetMap();
        result.offsetMap_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage) {
          return mergeFrom((com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage other) {
        if (other == com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage.getDefaultInstance()) return this;
        if (!other.getConsumer().isEmpty()) {
          consumer_ = other.consumer_;
          onChanged();
        }
        if (!other.getTopic().isEmpty()) {
          topic_ = other.topic_;
          onChanged();
        }
        internalGetMutableOffsetMap().mergeFrom(
            other.internalGetOffsetMap());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object consumer_ = "";
      /**
       * <code>string consumer = 1;</code>
       * @return The consumer.
       */
      public java.lang.String getConsumer() {
        java.lang.Object ref = consumer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          consumer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string consumer = 1;</code>
       * @return The bytes for consumer.
       */
      public com.google.protobuf.ByteString
          getConsumerBytes() {
        java.lang.Object ref = consumer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          consumer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string consumer = 1;</code>
       * @param value The consumer to set.
       * @return This builder for chaining.
       */
      public Builder setConsumer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        consumer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string consumer = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearConsumer() {
        
        consumer_ = getDefaultInstance().getConsumer();
        onChanged();
        return this;
      }
      /**
       * <code>string consumer = 1;</code>
       * @param value The bytes for consumer to set.
       * @return This builder for chaining.
       */
      public Builder setConsumerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        consumer_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object topic_ = "";
      /**
       * <code>string topic = 2;</code>
       * @return The topic.
       */
      public java.lang.String getTopic() {
        java.lang.Object ref = topic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          topic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string topic = 2;</code>
       * @return The bytes for topic.
       */
      public com.google.protobuf.ByteString
          getTopicBytes() {
        java.lang.Object ref = topic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string topic = 2;</code>
       * @param value The topic to set.
       * @return This builder for chaining.
       */
      public Builder setTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        topic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string topic = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTopic() {
        
        topic_ = getDefaultInstance().getTopic();
        onChanged();
        return this;
      }
      /**
       * <code>string topic = 2;</code>
       * @param value The bytes for topic to set.
       * @return This builder for chaining.
       */
      public Builder setTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        topic_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.Long> offsetMap_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Long>
      internalGetOffsetMap() {
        if (offsetMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              OffsetMapDefaultEntryHolder.defaultEntry);
        }
        return offsetMap_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Long>
      internalGetMutableOffsetMap() {
        onChanged();;
        if (offsetMap_ == null) {
          offsetMap_ = com.google.protobuf.MapField.newMapField(
              OffsetMapDefaultEntryHolder.defaultEntry);
        }
        if (!offsetMap_.isMutable()) {
          offsetMap_ = offsetMap_.copy();
        }
        return offsetMap_;
      }

      public int getOffsetMapCount() {
        return internalGetOffsetMap().getMap().size();
      }
      /**
       * <code>map&lt;int32, int64&gt; offsetMap = 3;</code>
       */

      @java.lang.Override
      public boolean containsOffsetMap(
          int key) {
        
        return internalGetOffsetMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getOffsetMapMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.Long> getOffsetMap() {
        return getOffsetMapMap();
      }
      /**
       * <code>map&lt;int32, int64&gt; offsetMap = 3;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.Integer, java.lang.Long> getOffsetMapMap() {
        return internalGetOffsetMap().getMap();
      }
      /**
       * <code>map&lt;int32, int64&gt; offsetMap = 3;</code>
       */
      @java.lang.Override

      public long getOffsetMapOrDefault(
          int key,
          long defaultValue) {
        
        java.util.Map<java.lang.Integer, java.lang.Long> map =
            internalGetOffsetMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, int64&gt; offsetMap = 3;</code>
       */
      @java.lang.Override

      public long getOffsetMapOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, java.lang.Long> map =
            internalGetOffsetMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearOffsetMap() {
        internalGetMutableOffsetMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int32, int64&gt; offsetMap = 3;</code>
       */

      public Builder removeOffsetMap(
          int key) {
        
        internalGetMutableOffsetMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.Long>
      getMutableOffsetMap() {
        return internalGetMutableOffsetMap().getMutableMap();
      }
      /**
       * <code>map&lt;int32, int64&gt; offsetMap = 3;</code>
       */
      public Builder putOffsetMap(
          int key,
          long value) {
        
        
        internalGetMutableOffsetMap().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int32, int64&gt; offsetMap = 3;</code>
       */

      public Builder putAllOffsetMap(
          java.util.Map<java.lang.Integer, java.lang.Long> values) {
        internalGetMutableOffsetMap().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SyncOffsetMessage)
    }

    // @@protoc_insertion_point(class_scope:SyncOffsetMessage)
    private static final com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage();
    }

    public static com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SyncOffsetMessage>
        PARSER = new com.google.protobuf.AbstractParser<SyncOffsetMessage>() {
      @java.lang.Override
      public SyncOffsetMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SyncOffsetMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SyncOffsetMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SyncOffsetMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.rabbitmq.protocol.message.SyncOffsetMessageOuterClass.SyncOffsetMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SyncOffsetMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SyncOffsetMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SyncOffsetMessage_OffsetMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SyncOffsetMessage_OffsetMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037message/SyncOffsetMessage.proto\"\234\001\n\021Sy" +
      "ncOffsetMessage\022\020\n\010consumer\030\001 \001(\t\022\r\n\005top" +
      "ic\030\002 \001(\t\0224\n\toffsetMap\030\003 \003(\0132!.SyncOffset" +
      "Message.OffsetMapEntry\0320\n\016OffsetMapEntry" +
      "\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\003:\0028\001B\037\n\035com." +
      "rabbitmq.protocol.messageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SyncOffsetMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SyncOffsetMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SyncOffsetMessage_descriptor,
        new java.lang.String[] { "Consumer", "Topic", "OffsetMap", });
    internal_static_SyncOffsetMessage_OffsetMapEntry_descriptor =
      internal_static_SyncOffsetMessage_descriptor.getNestedTypes().get(0);
    internal_static_SyncOffsetMessage_OffsetMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SyncOffsetMessage_OffsetMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
